// Copyright 2025 Asher Buk
// SPDX-License-Identifier: Apache-2.0
// https://github.com/AshBuk/FingerGo

/**
 * English Dvorak keyboard layout
 */
(() => {
    window.LAYOUT_EN_DVORAK = {
        id: 'en-dvorak',
        name: 'English (Dvorak)',
        language: 'en',

        rows: [
            [
                { key: '`', label: ['~', '`'] },
                { key: '1', label: ['!', '1'] },
                { key: '2', label: ['@', '2'] },
                { key: '3', label: ['#', '3'] },
                { key: '4', label: ['$', '4'] },
                { key: '5', label: ['%', '5'] },
                { key: '6', label: ['^', '6'] },
                { key: '7', label: ['&', '7'] },
                { key: '8', label: ['*', '8'] },
                { key: '9', label: ['(', '9'] },
                { key: '0', label: [')', '0'] },
                { key: '[', label: ['{', '['] },
                { key: ']', label: ['}', ']'] },
                { key: 'Backspace', label: 'Backspace', className: 'key-wide' },
            ],
            [
                { key: 'Tab', label: 'Tab', className: 'key-wide' },
                { key: "'", label: ['"', "'"] },
                { key: ',', label: ['<', ','] },
                { key: '.', label: ['>', '.'] },
                { key: 'p', label: 'P' },
                { key: 'y', label: 'Y' },
                { key: 'f', label: 'F' },
                { key: 'g', label: 'G' },
                { key: 'c', label: 'C' },
                { key: 'r', label: 'R' },
                { key: 'l', label: 'L' },
                { key: '/', label: ['?', '/'] },
                { key: '=', label: ['+', '='] },
                { key: '\\', label: ['|', '\\'], className: 'key-wide' },
            ],
            [
                { key: 'CapsLock', label: 'Caps', className: 'key-wider' },
                { key: 'a', label: 'A' },
                { key: 'o', label: 'O' },
                { key: 'e', label: 'E' },
                { key: 'u', label: 'U' },
                { key: 'i', label: 'I' },
                { key: 'd', label: 'D' },
                { key: 'h', label: 'H' },
                { key: 't', label: 'T' },
                { key: 'n', label: 'N' },
                { key: 's', label: 'S' },
                { key: '-', label: ['_', '-'] },
                { key: 'Enter', label: 'Enter', className: 'key-wider' },
            ],
            [
                { key: 'Shift', label: 'Shift', className: 'key-widest' },
                { key: ';', label: [':', ';'] },
                { key: 'q', label: 'Q' },
                { key: 'j', label: 'J' },
                { key: 'k', label: 'K' },
                { key: 'x', label: 'X' },
                { key: 'b', label: 'B' },
                { key: 'm', label: 'M' },
                { key: 'w', label: 'W' },
                { key: 'v', label: 'V' },
                { key: 'z', label: 'Z' },
                { key: 'Shift', label: 'Shift', className: 'key-widest' },
            ],
            [{ key: ' ', label: 'Space', className: 'key-space' }],
        ],

        fingerMap: {
            // Left hand - pinky (column 1)
            '`': 'left-pinky',
            1: 'left-pinky',
            "'": 'left-pinky',
            a: 'left-pinky',
            ';': 'left-pinky',
            Tab: 'left-pinky',
            CapsLock: 'left-pinky',
            // Left hand - ring (column 2)
            2: 'left-ring',
            ',': 'left-ring',
            o: 'left-ring',
            q: 'left-ring',
            // Left hand - middle (column 3)
            3: 'left-middle',
            '.': 'left-middle',
            e: 'left-middle',
            j: 'left-middle',
            // Left hand - index (columns 4-5)
            4: 'left-index',
            5: 'left-index',
            p: 'left-index',
            y: 'left-index',
            u: 'left-index',
            i: 'left-index',
            k: 'left-index',
            x: 'left-index',

            // Left hand - shift symbols
            '~': 'left-pinky',
            '!': 'left-pinky',
            '"': 'left-pinky',
            '@': 'left-ring',
            '<': 'left-ring',
            '#': 'left-middle',
            '>': 'left-middle',
            $: 'left-index',
            '%': 'left-index',

            // Right hand - index (columns 6-7)
            6: 'right-index',
            7: 'right-index',
            f: 'right-index',
            g: 'right-index',
            d: 'right-index',
            h: 'right-index',
            b: 'right-index',
            m: 'right-index',
            // Right hand - middle (column 8)
            8: 'right-middle',
            c: 'right-middle',
            t: 'right-middle',
            w: 'right-middle',
            // Right hand - ring (column 9)
            9: 'right-ring',
            r: 'right-ring',
            n: 'right-ring',
            v: 'right-ring',
            // Right hand - pinky (columns 10+)
            0: 'right-pinky',
            '[': 'right-pinky',
            ']': 'right-pinky',
            l: 'right-pinky',
            '/': 'right-pinky',
            '=': 'right-pinky',
            '\\': 'right-pinky',
            s: 'right-pinky',
            '-': 'right-pinky',
            z: 'right-pinky',
            Backspace: 'right-pinky',
            Enter: 'right-pinky',

            // Right hand - shift symbols
            '^': 'right-index',
            '&': 'right-index',
            '*': 'right-middle',
            '(': 'right-ring',
            ')': 'right-pinky',
            '{': 'right-pinky',
            '}': 'right-pinky',
            '?': 'right-pinky',
            '+': 'right-pinky',
            '|': 'right-pinky',
            _: 'right-pinky',
            ':': 'left-pinky',

            // Thumbs
            ' ': 'thumb',
        },

        // Keys that belong to left hand (for Shift logic)
        leftHandKeys: new Set([
            '`',
            '~',
            '1',
            '!',
            '2',
            '@',
            '3',
            '#',
            '4',
            '$',
            '5',
            '%',
            "'",
            '"',
            ',',
            '<',
            '.',
            '>',
            'p',
            'P',
            'y',
            'Y',
            'a',
            'A',
            'o',
            'O',
            'e',
            'E',
            'u',
            'U',
            'i',
            'I',
            ';',
            ':',
            'q',
            'Q',
            'j',
            'J',
            'k',
            'K',
            'x',
            'X',
            'Tab',
            'CapsLock',
        ]),

        // Map shift symbols to their base keys (for keyboard highlighting)
        shiftToBaseKey: {
            '~': '`',
            '!': '1',
            '@': '2',
            '#': '3',
            $: '4',
            '%': '5',
            '^': '6',
            '&': '7',
            '*': '8',
            '(': '9',
            ')': '0',
            '{': '[',
            '}': ']',
            '"': "'",
            '<': ',',
            '>': '.',
            '?': '/',
            '+': '=',
            '|': '\\',
            _: '-',
            ':': ';',
        },
    };
})();
